FROM python:3.11-slim

# Installer les dépendances système nécessaires pour psycopg2
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    iputils-ping \
    curl \
    gcc \
    g++ \
    make

WORKDIR /app

# Copier uniquement requirements.txt pour tirer parti du cache Docker
COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install debugpy

EXPOSE 5000
EXPOSE 5678

# Copier le reste des fichiers
COPY . .

ENV ENV_CONFIG=development

# Lancer le serveur de développement Flask
CMD ["python", "run.py"]